baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'PÃ¡gina de Alicia'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name = 'Inicio'
    pageRef = '/'
    weight = 10
  
  [[menu.main]]
    name = 'Alicia'
    pageRef = '/about'
    weight = 30
  